name: Build webpack
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - run: npm ci

      - run: npm run prod
      - run: git push origin master
